

#ifndef _CAR_CONFIG_H
#define _CAR_CONFIG_H

#define DELIMITADOR ","

#define SERIAL_VELOCIDADE 115200
#define PORT_HTTP 80
#define SSID_WIFI "CONTAB_ 2.4"
#define PASSWORD_WIFI "11851404"

#define SERVO_DIRECAO_PIN 12
#define SERVO_CENTRO 80
#define SERVO_DIRECAO_MAX 130
#define SERVO_DIRECAO_MIN 35
#define SERVO_ADICAO_SUBTRACAO 5

#define SERVO_MEDICAO_PIN 23
#define SERVO_MEDICAO_PASSO 5
#define TIMEOUT_NILLIS 50

#define MOTOR_IN1_A 33
#define MOTOR_IN1_B 32
#define MOTOR_1_PWM 25
#define PWM_MOTOR_FREQUENCY 200
#define PWM_MOTOR_RESOLUTION 8
#define MOTOR_ADICAO_SUBTRACAO 20

#endif